enquiry/urls.py
from django.urls import path
from django.views.generic import TemplateView

from enquiry.views import IndexView, CourseDetailView, ContactView, StudentEnrollmentView, CourseListView

app_name = 'enquiry'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('course/<slug:slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('contact', ContactView.as_view(), name='contact'),
    path('enroll', StudentEnrollmentView.as_view(), name='enroll'),
    path('admissions', TemplateView.as_view(template_name='academics/admissions.html'), name='admission'),
    path('about', TemplateView.as_view(template_name='academics/about.html'), name='about'),
    path('courses', CourseListView.as_view(), name='course_list'),
]

followUp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('enquiry.urls')),
    path('user/', include('user.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from user.views import signup, UserLoginView, UserRegisterView

app_name = 'user'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
]

templates/academics/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Academics &mdash; Website by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'academics/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'academics/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'academics/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'academics/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'academics/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'academics/css/owl.theme.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'academics/css/jquery.fancybox.min.css' %}">

    <link rel="stylesheet" href="{% static 'academics/css/bootstrap-datepicker.css' %}">

    <link rel="stylesheet" href="{% static 'academics/fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'academics/css/aos.css' %}">
    <link href="{% static 'academics/css/jquery.mb.YTPlayer.min.css' %}" media="all" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="{% static 'academics/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'academics/css/ambiance.css' %}">

</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

<div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
                <span class="icon-close2 js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>


    <div class="py-2 bg-light">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-9 d-none d-lg-block">
                    <a href="#" class="small mr-3"><span class="icon-question-circle-o mr-2"></span> Have a
                        questions?</a>
                    <a href="#" class="small mr-3"><span class="icon-phone2 mr-2"></span> 10 20 123 456</a>
                    <a href="#" class="small mr-3"><span class="icon-envelope-o mr-2"></span> info@mydomain.com</a>
                </div>
                <div class="col-lg-3 text-right">
                    {% if not request.user.is_authenticated %}
                        <a href="{% url 'user:login' %}" class="small mr-3"><span class="icon-unlock-alt"></span> Log In</a>
                        <a href="{% url 'user:register' %}" class="small btn btn-primary px-4 py-2 rounded-0"><span
                                class="icon-users"></span> Register</a>
                    {% else %}
                        <a href="{% url 'user:logout' %}" class="small mr-3 text-danger"><span
                                class="icon-power-off"></span> Logout</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <header class="site-navbar py-4 js-sticky-header site-navbar-target" role="banner">

        <div class="container">
            <div class="d-flex align-items-center">
                <div class="site-logo">
                    <a href="{% url 'enquiry:index' %}" class="d-block">
                        <img src="{% static 'academics/images/logo.jpg' %}" alt="Image" class="img-fluid">
                    </a>
                </div>
                <div class="mr-auto">
                    <nav class="site-navigation position-relative text-right" role="navigation">
                        <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                            <li class="{% if request.path == '/' %}active {% endif %}">
                                <a href="{% url 'enquiry:index' %}" class="nav-link text-left">Home</a>
                            </li>
                            <li class="{% if request.path == '/about' %}active {% endif %}">
                                <a href="{% url 'enquiry:about' %}" class="nav-link text-left">
                                    About Us
                                </a>
                            </li>
                            <li class="{% if request.path == '/admissions' %}active {% endif %}">
                                <a href="{% url 'enquiry:admission' %}" class="nav-link text-left">Admissions</a>
                            </li>
                            <li class="{% if request.path == '/courses' %}active {% endif %}">
                                <a href="{% url 'enquiry:course_list' %}" class="nav-link text-left">Courses</a>
                            </li>
                            <li class="{% if request.path == '/contact' %}active {% endif %}">
                                <a href="{% url 'enquiry:contact' %}" class="nav-link text-left">Contact</a>
                            </li>
                        </ul>
                    </nav>

                </div>
                <div class="ml-auto">
                    <div class="social-wrap">
                        <a href="#"><span class="icon-facebook"></span></a>
                        <a href="#"><span class="icon-twitter"></span></a>
                        <a href="#"><span class="icon-linkedin"></span></a>

                        <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black"><span
                                class="icon-menu h3"></span></a>
                    </div>
                </div>

            </div>
        </div>

    </header>

    {% block content %}
    {% endblock %}

    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <p class="mb-4"><img src="{% static 'academics/images/logo.png' %}" alt="Image" class="img-fluid">
                    </p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nemo minima qui dolor, iusto
                        iure.</p>
                    <p><a href="#">Learn More</a></p>
                </div>
                <div class="col-lg-3">
                    <h3 class="footer-heading"><span>Our Campus</span></h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Acedemic</a></li>
                        <li><a href="#">News</a></li>
                        <li><a href="#">Our Interns</a></li>
                        <li><a href="#">Our Leadership</a></li>
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">Human Resources</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h3 class="footer-heading"><span>Our Courses</span></h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Math</a></li>
                        <li><a href="#">Science &amp; Engineering</a></li>
                        <li><a href="#">Arts &amp; Humanities</a></li>
                        <li><a href="#">Economics &amp; Finance</a></li>
                        <li><a href="#">Business Administration</a></li>
                        <li><a href="#">Computer Science</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h3 class="footer-heading"><span>Contact</span></h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Help Center</a></li>
                        <li><a href="#">Support Community</a></li>
                        <li><a href="#">Press</a></li>
                        <li><a href="#">Share Your Story</a></li>
                        <li><a href="#">Our Supporters</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


</div>
<!-- .site-wrap -->


<!-- loader -->
<div id="loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#51be78"/>
    </svg>
</div>

<script src="{% static 'academics/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'academics/js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'academics/js/jquery-ui.js' %}"></script>
<script src="{% static 'academics/js/popper.min.js' %}"></script>
<script src="{% static 'academics/js/bootstrap.min.js' %}"></script>
<script src="{% static 'academics/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'academics/js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'academics/js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'academics/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'academics/js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'academics/js/aos.js' %}"></script>
<script src="{% static 'academics/js/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'academics/js/jquery.sticky.js' %}"></script>
<script src="{% static 'academics/js/jquery.mb.YTPlayer.min.js' %}"></script>


<script src="{% static 'academics/js/main.js' %}"></script>
<script src="{% static 'academics/js/ambiance.js' %}"></script>

{% if messages %}
    {% for message in messages %}
        <script>
          {% if message.tags == 'success' %}
            toastr.success('{{ message }}')
          {% elif message.tags == 'error' %}
            toastr.error('{{ message }}')
          {% else %}
            toastr.info('{{ message }}')
          {% endif %}
        </script>
    {% endfor %}
{% endif %}
</body>

</html>

templates/academics/course-single.html
{% extends 'academics/base.html' %}
{% block content %}
    {% load staticfiles %}
    {% load enquiry %}
    <div class="site-section ftco-subscribe-1 site-blocks-cover pb-4"
         style="background-image: url('{% static "academics/images/bg_1.jpg" %}')">
        <div class="container">
            <div class="row align-items-end">
                <div class="col-lg-7">
                    <h2 class="mb-0">{{ course.title }}</h2>
                    <p>{{ course.excerpt }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="custom-breadcrumns border-bottom">
        <div class="container">
            <a href="{% url 'enquiry:index' %}">Home</a>
            <span class="mx-3 icon-keyboard_arrow_right"></span>
            <a href="courses.html">Courses</a>
            <span class="mx-3 icon-keyboard_arrow_right"></span>
            <span class="current">{{ course.title }}</span>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-md-6 mb-4">
                    <p>
                        <img src="{{ course.image.url }}" alt="Image" class="img-fluid">
                    </p>

                    <p class="text-center">
                        {% if request.user.is_authenticated %}
                            {% has_already_enrolled request.user course as already_enrolled %}
                            {% if already_enrolled %}
                                <a href="javascript:;"
                                   class="btn btn-primary rounded-0 btn-lg px-5 text-center"
                                   style="width: 100%"
                                >
                                    You have already applied for this Course
                                </a>
                            {% else %}
                                <a href="#"
                                   class="btn btn-primary rounded-0 btn-lg px-5 text-center"
                                   style="width: 100%"
                                   data-toggle="modal"
                                   data-target="#exampleModalCenter"
                                >
                                    Enroll For This Course
                                </a>
                            {% endif %}
                        {% else %}
                            <a href="{% url 'enquiry:contact' %}"
                               class="btn btn-primary rounded-0 btn-lg px-5 text-center"
                               style="width: 100%"
                            >
                                Enquire For This Course
                            </a>
                        {% endif %}
                    </p>

                </div>
                <div class="col-lg-5 ml-auto align-self-center">
                    <div class="mb-5">
                        <h4 class="section-title-underline mb-3s">
                            <span>Shifts</span>
                        </h4>
                        {% for course_shift in course.course_shifts.all %}
                            <div>
                                <span class="text-black font-weight-bold">{{ course_shift.shift }}: </span>
                                <span class="mx-2">{{ course_shift.shift.start_time }} &mdash; {{ course_shift.shift.end_time }}</span>
                                {% if course_shift.has_remaining_seats %}
                                    <span class="text-success font-weight-bold">( {{ course_shift.remaining_seats }} Seats Remaining )</span>
                                {% else %}
                                    <span class="text-danger">( No Seats Available )</span>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    <h2 class="section-title-underline mb-5">
                        <span>Course Details</span>
                    </h2>
                    <div>
                        {{ course.extra_information | safe }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'snippets/philoshophy.html' %}

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Enroll In Course:
                        <span class="font-weight-bold">{{ course }}</span>
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="post" action="{% url 'enquiry:enroll' %}">
                    <div class="modal-body">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="exampleFormControlSelect1">Preferred Shift</label>
                            <select class="form-control" id="exampleFormControlSelect1" name="shift">
                                {% for course_shift in course.course_shifts.all %}
                                    <option value="{{ course_shift.id }}">{{ course_shift.shift }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        {% if not requser.user.student %}
                            <div class="form-group">
                                <label for="number">Contact Number</label>
                                <input type="text" class="form-control" id="number" placeholder="number"
                                       name="phone_number">
                            </div>
                            <div class="form-group">
                                <label for="location">Location</label>
                                <input type="text" class="form-control" id="location" placeholder="location" name="location">
                            </div>
                            <div class="form-group">
                                <label for="educationLevel">Education Level</label>
                                <select class="form-control" id="educationLevel" name="education_level">
                                    <option value="Slc">Slc</option>
                                    <option value="Intermediate">Intermediate</option>
                                    <option value="Bachelor">Bachelor</option>
                                    <option value="Master">Master</option>
                                </select>
                            </div>
                        {% endif %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Enroll</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/academics/courses.html
{% extends 'academics/base.html' %}
{% block content %}
    {% load staticfiles %}
    {% load humanize %}
    <div class="site-section ftco-subscribe-1 site-blocks-cover pb-4"
         style="background-image: url({% static 'academics/images/bg_1.jpg' %})">
        <div class="container">
            <div class="row align-items-end">
                <div class="col-lg-7">
                    <h2 class="mb-0">Courses</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="custom-breadcrumns border-bottom">
        <div class="container">
            <a href="{% url 'enquiry:index' %}">Home</a>
            <span class="mx-3 icon-keyboard_arrow_right"></span>
            <span class="current">Courses</span>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            <div class="row">
                {% for course in courses %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="course-1-item">
                            <figure class="thumnail">
                                <a href="{% url 'enquiry:course_detail' slug=course.slug %}">
                                    <img src="{{ course.image.url }}" alt="Image" class="img-fluid">
                                </a>
                                <div class="price">Rs. {{ course.cost|intcomma }}</div>
                                <div class="category"><h3>{{ course.title }}</h3></div>
                            </figure>
                            <div class="course-1-content pb-4" title="Click Enroll in This Course to know more about this course">
                                <h2>{{ course.excerpt }}</h2>
                                <p class="desc mb-4">
                                    {{ course.extra_information| safe | truncatechars:'85' }}
                                </p>
                                <p>
                                    <a href="{% url 'enquiry:course_detail' slug=course.slug %}"
                                       class="btn btn-primary rounded-0 px-4">Enroll In This Course
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="course-1-item">
                        <figure class="thumnail">
                            <a href="course-single.html"><img src="images/course_2.jpg" alt="Image"
                                                              class="img-fluid"></a>
                            <div class="price">$99.00</div>
                            <div class="category"><h3>Mobile Application</h3></div>
                        </figure>
                        <div class="course-1-content pb-4">
                            <h2>How To Create Mobile Apps Using Ionic</h2>
                            <div class="rating text-center mb-3">
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                            </div>
                            <p class="desc mb-4">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique
                                accusantium ipsam.</p>
                            <p><a href="course-single.html" class="btn btn-primary rounded-0 px-4">Enroll In This
                                Course</a></p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="course-1-item">
                        <figure class="thumnail">
                            <a href="course-single.html"><img src="images/course_3.jpg" alt="Image"
                                                              class="img-fluid"></a>
                            <div class="price">$99.00</div>
                            <div class="category"><h3>Mobile Application</h3></div>
                        </figure>
                        <div class="course-1-content pb-4">
                            <h2>How To Create Mobile Apps Using Ionic</h2>
                            <div class="rating text-center mb-3">
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                            </div>
                            <p class="desc mb-4">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique
                                accusantium ipsam.</p>
                            <p><a href="course-single.html" class="btn btn-primary rounded-0 px-4">Enroll In This
                                Course</a></p>
                        </div>
                    </div>
                </div>


                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="course-1-item">
                        <figure class="thumnail">
                            <a href="course-single.html"><img src="images/course_4.jpg" alt="Image"
                                                              class="img-fluid"></a>
                            <div class="price">$99.00</div>
                            <div class="category"><h3>Mobile Application</h3></div>
                        </figure>
                        <div class="course-1-content pb-4">
                            <h2>How To Create Mobile Apps Using Ionic</h2>
                            <div class="rating text-center mb-3">
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                            </div>
                            <p class="desc mb-4">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique
                                accusantium ipsam.</p>
                            <p><a href="course-single.html" class="btn btn-primary rounded-0 px-4">Enroll In This
                                Course</a></p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="course-1-item">
                        <figure class="thumnail">
                            <a href="course-single.html"><img src="images/course_5.jpg" alt="Image"
                                                              class="img-fluid"></a>
                            <div class="price">$99.00</div>
                            <div class="category"><h3>Mobile Application</h3></div>
                        </figure>
                        <div class="course-1-content pb-4">
                            <h2>How To Create Mobile Apps Using Ionic</h2>
                            <div class="rating text-center mb-3">
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                            </div>
                            <p class="desc mb-4">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique
                                accusantium ipsam.</p>
                            <p><a href="course-single.html" class="btn btn-primary rounded-0 px-4">Enroll In This
                                Course</a></p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="course-1-item">
                        <figure class="thumnail">
                            <a href="course-single.html"><img src="images/course_6.jpg" alt="Image"
                                                              class="img-fluid"></a>
                            <div class="price">$99.00</div>
                            <div class="category"><h3>Mobile Application</h3></div>
                        </figure>
                        <div class="course-1-content pb-4">
                            <h2>How To Create Mobile Apps Using Ionic</h2>
                            <div class="rating text-center mb-3">
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                                <span class="icon-star2 text-warning"></span>
                            </div>
                            <p class="desc mb-4">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique
                                accusantium ipsam.</p>
                            <p><a href="course-single.html" class="btn btn-primary rounded-0 px-4">Enroll In This
                                Course</a></p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    {% include 'snippets/philoshophy.html' %}
{% endblock %}

templates/academics/login.html
{% extends 'academics/base.html' %}
{% block content %}
    {% load staticfiles %}
    <div class="site-section ftco-subscribe-1 site-blocks-cover pb-4" style="background-image: url('images/bg_1.jpg')">
        <div class="container">
            <div class="row align-items-end justify-content-center text-center">
                <div class="col-lg-7">
                    <h2 class="mb-0">Login</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                </div>
            </div>
        </div>
    </div>


    <div class="custom-breadcrumns border-bottom">
        <div class="container">
            <a href="{% url 'enquiry:index' %}">Home</a>
            <span class="mx-3 icon-keyboard_arrow_right"></span>
            <span class="current">Login</span>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            <form class="form" method="post">
                {% csrf_token %}
                <div class="row justify-content-center">
                    <div class="text-danger">
                        {{ form.non_field_errors }}
                    </div>
                    <div class="col-md-5">
                        <div class="row">
                            <div class="col-md-12 form-group">
                                <label for="username">Username</label>
                                {{ form.username }}
                                <div class="text-danger">
                                    {{ form.username.errors }}
                                </div>
                            </div>
                            <div class="col-md-12 form-group">
                                <label for="passwords">Password</label>
                                {{ form.password }}
                                <div class="text-danger">
                                    {{ form.password.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <input type="submit" value="Log In" class="btn btn-primary btn-lg px-5">
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}